### ISSUE TITLE
[question] calculate Pseudo-Character Center(PCC) positions

### ISSUE THREAD

**Issue by riku0325** [clovaai/CLEval#4]
I have a question about eq.1 of [your paper](https://arxiv.org/abs/2006.06244).

(mistake)
![CodeCogsEqn](https://user-images.githubusercontent.com/40652406/89185764-b767b980-d5d5-11ea-8aa3-ab9b520c53a7.png)
(In my opinion)
![CodeCogsEqn-2](https://user-images.githubusercontent.com/40652406/89185843-da926900-d5d5-11ea-9765-57434ed67a9a.png)

Is this correct?

**Comment by chunchet-ng** [comment]
HI there,

Yes. I noticed the same issue as yours. 

The code implementation also does not match the equation in the paper, specifically on line [158](https://github.com/clovaai/CLEval/blob/03d05580a986e5af9b708ca8276da81abb41d12d/box_types.py#L158) and [159](https://github.com/clovaai/CLEval/blob/03d05580a986e5af9b708ca8276da81abb41d12d/box_types.py#L159) of [box_types.py](https://github.com/clovaai/CLEval/blob/03d05580a986e5af9b708ca8276da81abb41d12d/box_types.py).

The correct implementation should be:

`x = p1[0] + unit_x * i - unit_x / 2`
`y = p1[1] + unit_y * i - unit_y / 2`

or

`x = p1[0] * (1- (2*i-1)/(2*length)) + p2[0] * (2*i-1)/(2*length)`
`y = p1[1] * (1- (2*i-1)/(2*length)) + p2[1] * (2*i-1)/(2*length)`

Let me know if i made any mistakes.
